[env]
GO111MODULE = "on"
GOFLAGS = "-mod=readonly"

[tasks.dev]
description = "Run the application in development mode"
run = "go run ./cmd/cli"

[tasks.lint]
description = "Run golangci-lint"
run = "golangci-lint run"

[tasks.lint-fix]
description = "Fix golangci-lint issues automatically"
run = "golangci-lint run --fix"

[tasks.fmt]
description = "Format code"
run = "golangci-lint fmt"

[tasks.test]
description = "Run tests"
run = "go run gotest.tools/gotestsum@v1.12.2"

[tasks.test-coverage]
description = "Run tests with coverage"
run = "mise run test -- -- -cover ./..."

[tasks.build-snapshot]
description = "Build the application with version info"
run = "goreleaser release --clean --snapshot"

[tasks.clean]
description = "Remove generated files"
run = """
rm -rf bin/
go clean
"""

[settings]
idiomatic_version_file_enable_tools = ["go"]
