name: goreleaser

on:
  push:
    tags:
      - "v*"

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  id-token: write
  packages: write
  attestations: write

jobs:
  release:
    runs-on: ubuntu-24.04
    if: github.repository == 'sushichan044/glob-frontmatter'
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - uses: ./.github/workflows/composite/setup
        with:
          go-version-file: go.mod

      - uses: goreleaser/goreleaser-action@e435ccd777264be153ace6237001ef4d979d3a7a # v6.4.0
        with:
          args: release --clean
          version: "~> v2"

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAP_GITHUB_TOKEN: ${{ secrets.TAP_GITHUB_TOKEN }}

      - uses: actions/attest-build-provenance@e8998f949152b193b063cb0ec769d69d929409be # v2.4.0
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        with:
          subject-checksums: ./dist/checksums.txt
