name: goreleaser

on:
  push:
    tags:
      - "v*"

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  id-token: write
  packages: write
  attestations: write

jobs:
  release:
    runs-on: ubuntu-24.04
    if: github.repository == 'sushichan044/mdfm'
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0

      - uses: ./.github/workflows/composite/setup
        with:
          go-version-file: go.mod

      - uses: goreleaser/goreleaser-action@e435ccd777264be153ace6237001ef4d979d3a7a # v6.4.0
        with:
          args: release --clean
          version: "~> v2"

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAP_GITHUB_TOKEN: ${{ secrets.TAP_GITHUB_TOKEN }}

      - uses: actions/attest-build-provenance@977bb373ede98d70efdf65b84cb5f73e068dcc2a # v3.0.0
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        with:
          subject-checksums: ./dist/checksums.txt
